name: social_seniors_prototype
description: Companionship app prototype.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  image_picker: ^1.0.7
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.9.0
  table_calendar: ^3.1.1
  intl: ^0.19.0
  speech_to_text: ^6.6.0
  flutter_sound: ^10.0.0

flutter:
  uses-material-design: true
